### ISSUE TITLE
Resource files are needing update

### ISSUE THREAD

**Issue by brullsker** [character-map-uwp/Character-Map-UWP#10]
In the resource files, only the strings of the main page (and some of about) are included. The strings of the following parts of the app aren't included yet:
- main page's app bar
- settings
- on about: Thanks-section

**Comment by EdiWang** [comment]
Thanks. However I do not know German. I may use machine translator to do this. If there's any mistake, please let me know

**Comment by JohnnyWestlake** [comment]
closing in favour of #149  (which is pinned)
