### ISSUE TITLE
[Feature Request] add back Copy Symbol in code

### ISSUE THREAD

**Issue by uponatime2019** [character-map-uwp/Character-Map-UWP#101]
In the old version I can easily copy symbol in code like this
`(Symbol)0xE7FC,`
But it missing in recent releases, can you add it back?

**Comment by JohnnyWestlake** [comment]
If you want the C# version of the Symbol, there is an option to toggle between C# & XAML in the Settings view. Otherwise it's currently only showing Symbol when it is actually a valid cast - which is only on Segoe MDL2 Asset for support enum values.
