### ISSUE TITLE
Option to disable font fallback in Type Ramp view.

### ISSUE THREAD

**Issue by be5invis** [character-map-uwp/Character-Map-UWP#110]
It would be good to have an option in the Type Ramp view so that font fallback will no longer applied, and unsupported characters are displayed in Tofu's.

**Comment by JohnnyWestlake** [comment]
I've actually looked at this before - so XAML currently doesn't let you *remove* the default Fallback font it use, but it does let you manually specify another. But unless that font has every single possible glyph in it, it still falls back to the system default font afterwards. The only font I know of that comes close to fitting that is LastResort (with 388232 codepoints covered by ~ 6000 glyphs), but it's not performant to use, and it's fallback characters are not ideal for this circumstance.

Like some of the other issues, waiting for WinUI will let us / someone have an option to change this in the UI layer itself. A manual DirectWrite text render is also possible but has performance problems. (Or if anyone can happily create a blank font that lists codepoints continuously up to U+10FFFF with a single glyph I can see how that works).
