### ISSUE TITLE
Fonts loaded when the app is open aren't displayed until the app is restarted

### ISSUE THREAD

**Issue by mrlacey** [character-map-uwp/Character-Map-UWP#152]
Repro:

- open app
- install new font on machine
- app detects new fonts installed and gives option to reload available fonts
- reload/sync fonts
- newly installed font now visible in the app BUT is not used in the app for the displayed characters
- restart app
- CAN now see the new font being used

**Comment by JohnnyWestlake** [comment]
Initially I had chalked this down to this down to a problem with the XAML's own font cache not being aware of the font, but I've not been able to confirm that outside of "it should just work", so I'll take another look and see if there's anything that can be done.
