### ISSUE TITLE
Add an option to disable animations

### ISSUE THREAD

**Issue by MarcAnt01** [character-map-uwp/Character-Map-UWP#158]
I really like the app, but I find animations very slow and annoying, could you an option to disable them?

**Comment by JohnnyWestlake** [comment]
The following existing option should cover you for the most part.

![image](https://user-images.githubusercontent.com/2319473/103584062-d053fe00-4ed8-11eb-9d77-e66ebd006ef9.png)

**Comment by MarcAnt01** [comment]
@JohnnyWestlake actually my complaints are mostly about settings animations that aren't touched
