### ISSUE TITLE
[Feature Request] WinUI 2.6

### ISSUE THREAD

**Issue by Tropix126** [character-map-uwp/Character-Map-UWP#171]
The WinUI team announced WinUI 2.6 two days ago (microsoft/microsoft-ui-xaml#5262), which introduces new styles and materials to the drawing board. Are there plans to make the upgrade?

**Comment by JohnnyWestlake** [comment]
No immediate plans from my point of view. I'm actually intending on removing the WinUI library entirely at some point to increase start-up performance and reduce the application footprint, given it's barely used in the app. The recently WinUI design changes wouldn't have much of any impact on the current design style of the app either way (which is not strictly following any version of their design guidelines, but following what works best for the app)
