### ISSUE TITLE
The name of the app is confusing

### ISSUE THREAD

**Issue by MarcAnt01** [character-map-uwp/Character-Map-UWP#174]
I have just noticed that the app appears as "Character Map" and no longer as "Character Map UWP". I wasn't a fan of "uwp" in the name, but I think naming it in the same way of the inbox Windows app is quite confusing. Are there any plans to change the name to something else (for example Modern Character Map)?

**Comment by JohnnyWestlake** [comment]
No plans to change it from my side, but I also have no idea why the display name is different for you. Are you perchance using Windows 11 Preview now? It's possible it's picking up a different name than Windows 10 did. As far as I can see we haven't touched the names in over 2 years, so nothing *should* have changed 🤔

**Comment by MarcAnt01** [comment]
> No plans to change it from my side, but I also have no idea why the display name is different for you. Are you perchance using Windows 11 Preview now? It's possible it's picking up a different name than Windows 10 did. As far as I can see we haven't touched the names in over 2 years, so nothing *should* have changed 🤔

Yes, using W11 here

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/127210526-52de3a92-7258-4fb6-8d81-ea56e011f668.png)
For reference

**Comment by ray1997** [comment]
It's look like the name was taken from text resource... You can submit a UWP suffix if you want.
https://github.com/character-map-uwp/Character-Map-UWP/blob/5ddce2817809d4ea25873ee0d6f039fb1d98c9bc/CharacterMap/CharacterMap/Strings/en-US/Resources.resw#L124
