### ISSUE TITLE
Unable to switch to type ramp view after opening a woff font file

### ISSUE THREAD

**Issue by br45entei** [character-map-uwp/Character-Map-UWP#187]
I opened a woff file by double clicking on it, and then clicked on the "switch to type ramp view" button.
However, instead of the usual screen with a slider, an error message popped up.
I have attached the woff file so that you may test/debug with it.
(It's one of Google's free fonts, "Lora Regular", converted from *.ttf)
[LoraRegular.zip](https://github.com/character-map-uwp/Character-Map-UWP/files/7615072/LoraRegular.zip)

```
The parameter is incorrect.

target

```

**OS Version**: 10.0.19043.1288
**OS Architecture**: X64
**App Version**: 2021.7.4.0
**App Culture**: en-US

**Comment by hyphenminus** [comment]
Same problem when viewing non-installed .ttf and .otf fonts:

Character Map UWP reports an error when attempting to switch to Type Ramp view to see variable font features after opening fonts that are not installed.

Crash report:
```
The parameter is incorrect.
target
```
**OS Version**: 10.0.19044.1526
**OS Architecture**: X64
**App Version**: 2021.7.4.0
**App Culture**: en-GB

**Comment by codeman38** [comment]
Same issue here, after opening a TTF that's not installed.


```
The parameter is incorrect.

target

```

**OS Version**: 10.0.19044.1586
**OS Architecture**: X64
**App Version**: 2021.7.4.0
**App Culture**: en-US

**Comment by JohnnyWestlake** [comment]
Fwiw, finally got around to fixing this, probably won't push the branch for another week or so but the fix is coming! Apologies for taking so long with it

**Comment by hyphenminus** [comment]
Thanks! In the fix description, does “remove entries not supported by external files” mean that some features (such as Type Ramp, including variable font axes) will not be visible for font files that are not installed? If so, would there instead be a way to access the relevant data to display such features without having to install the font (in the same way that characters and OpenType variations are already viewable without having to install)?

**Comment by JohnnyWestlake** [comment]
Only adding external files to collections and viewing them in quick compare are disabled, so Type Ramp & Variation Axis should work fine for all of them!

**Comment by hyphenminus** [comment]
Brilliant, thank you!
