### ISSUE TITLE
Box Characters not showing

### ISSUE THREAD

**Issue by edwinbradford** [character-map-uwp/Character-Map-UWP#188]
When viewing the font "Source Sans Pro" multiple Box Characters such as U+251C are not listed in the Characters Pane. The same Box Characters are verified as present in the font by viewing it in Windows Character Map under Unicode Subrange "Box Characters".

I became aware of the issue because I was using Source Sans Pro in Notepad++ and was able to enter the characters but not able to browse them in Character Map UWP.

I hope this can be resolved because Character Map UWP is infinitely superior to Windows Character Map but it does need to be accurate for me to use it.

**Comment by JohnnyWestlake** [comment]
Do you know what version of Source Sans Pro you're using? The ones I have installed show fine 🤔
