### ISSUE TITLE
Possible migrate to Windows App SDK?

### ISSUE THREAD

**Issue by JohnCido** [character-map-uwp/Character-Map-UWP#189]
As described in the title, do you plan to move to the Windows App SDK?
I forked the repo and have some interest in doing so. But this might change the minimum Windows version, etc. And WinAppSDK has limited support of certain features too.

**Comment by JohnnyWestlake** [comment]
At the moment, absolutely not. The performance and stability of the App SDK are notably than UWP XAML at the moment so there is no advantage of doing so - only a worse experience for the end user - and it doesnt look like this is going to change for a long, long while. 

The only thing that might makemit convincing is if and when they eventually opensource then tire AppSDK XAML platform, at which point we could potentially improve the XAML layer TextBlock to properly render variable fonts & advanced typography etc without directly interfacing with DirectWrite, but even though that was an original promise of the project reunion that's starting to look unlikely, for the near term future at least anyway

**Comment by JohnCido** [comment]
> At the moment, absolutely not. The performance and stability of the App SDK are notably than UWP XAML at the moment so there is no advantage of doing so - only a worse experience for the end user - and it doesnt look like this is going to change for a long, long while.
> 
> The only thing that might makemit convincing is if and when they eventually opensource then tire AppSDK XAML platform, at which point we could potentially improve the XAML layer TextBlock to properly render variable fonts & advanced typography etc without directly interfacing with DirectWrite, but even though that was an original promise of the project reunion that's starting to look unlikely, for the near term future at least anyway

Solid point. I guess we'll have to wait and see if everything works in the future.
