### ISSUE TITLE
Terminal font

### ISSUE THREAD

**Issue by aplocher** [character-map-uwp/Character-Map-UWP#19]
Thanks for the great tool.  Is there a way to view the Terminal font? 
![image](https://user-images.githubusercontent.com/1132447/34864598-dea7aec0-f729-11e7-8c10-5ba0401aaae9.png)

**Comment by yoshiask** [comment]
I presume this has something to do with the fact that the Terminal font is neither OpenType or TrueType

**Comment by JohnnyWestlake** [comment]
Yes, DirectWrite does not actually support the legacy bitmapped format Terminal is using, so will likely never be seen in XAML.
