### ISSUE TITLE
Will not export to png or svg

### ISSUE THREAD

**Issue by Mike134** [character-map-uwp/Character-Map-UWP#215]
When attempting to save a character as a png or svg, an empty file is created and then the following message is displayed
This happens on two different systems.  Win 11 22H2 22622.598 and Win 11 22H2 22621.521.  
Character Map UWP - 2022.2.4.0 (X64)

![image](https://user-images.githubusercontent.com/2112582/190922904-5dde6ae3-afb6-4f36-aded-e8cf3a9bf3b7.png)

**Comment by JohnnyWestlake** [comment]
Hi, thanks for the report. Does this occur on all fonts or just a particular font? I have yet to be able to reproduce this with any of the fonts I have on hand

**Comment by drofnarc** [comment]
I am also having the same issue.  I have used this character map in the past with no problems at all.  This is the first time I have had an issue with it and have and  every font I have tried gets the same response.  I get the same response saying no such interface supported.  I am using System 11.

**Comment by ray1997** [comment]
Weird, I am on the same Windows 11 version; although Stable ring. (22H2/22621.674) and able to save the glyph from font Segoe UI Emoji just fine..

**Comment by eminterrupted** [comment]
Hello, I am also experiencing this. Here's some info that hopefully will be helpful. Let me know if you'd like anything else!

- I tried it with 2 system fonts (Calibri, Segoe UI) and 1 user-installed font (CaskaydiaCove Nerd Font) without success
- The file gets created, but it's a 0B file
- I've tried all four options (black and white fills on svg and png formats), and all experience this issue
- Version info
  - Windows: 22H2 22623.875 
  - Character Map UWP: 2022.2.6.0

**Comment by ray1997** [comment]
@JohnnyWestlake Will you be able to look into this? As I'm now able to reproduce it, but I have no idea what magic stuff going on in C++ side of codes.
The problem I'm guessing is about File sync on OneDrive? As saving to other folder outside OneDrive folder is working just fine, but as soon as saving file on OneDrive this happen:
![image](https://user-images.githubusercontent.com/14814401/201844163-6bb6cd43-ef5d-4ebb-ad83-3f078710d2a2.png)

The targetFolder ended up being null and I have no idea why :/

**Comment by ray1997** [comment]
Apologize for the mass pings, but none of you provide this crucial details. "Where did you save the files" and if you save on "Documents", "Desktop", or "Pictures" does it sync to online file provider? (Like OneDrive or Dropbox) 
@Mike134  @drofnarc  @eminterrupted

**Comment by JohnnyWestlake** [comment]
This should be fixed in the latest update on the store. Thanks for the reports folks! And feel free to open this back up if you're still having issues.
