### ISSUE TITLE
App won't see fonts with non-latin names

### ISSUE THREAD

**Issue by swoy45** [character-map-uwp/Character-Map-UWP#219]
Hello! I've downloaded this Chinese font and installed it. Apps like Illustrator and Figma seeing it correctly, system fonts menu and classic Character Map also can find it. However this app can't, it's not in the list after app restart.
Here are font homepage and screenshot of what is happening after install:
https://www.freechinesefont.com/simplified-mini-jian-yi-hei-download/
![image](https://user-images.githubusercontent.com/17198492/202719021-9048ee53-4c37-45bf-972c-254aa4b7030a.png)

**Comment by JohnnyWestlake** [comment]
FWIW, the app does recognise the font (you'll find it at the very bottom of the font list), but for some reason it's loading it with an incorrect / corrupted font name. Will have to investigate why.
