### ISSUE TITLE
Context menu can't be opened with keyboard

### ISSUE THREAD

**Issue by JaiganeshKumaran** [character-map-uwp/Character-Map-UWP#229]
The context menu for glyphs can't be opened with the keyboard (either Shift+F10 or the dedicated key). It also doesn't open when right-clicking in the last few pixels of the item with a mouse.

**Comment by JohnnyWestlake** [comment]
Thanks - addressed. Next build will probably be out at somepoint this month when I'm done fixing the new tabbed interface.
