### ISSUE TITLE
Full screen toggle button's icon doesn't change when using keyboard shortcut

### ISSUE THREAD

**Issue by JaiganeshKumaran** [character-map-uwp/Character-Map-UWP#231]
When using the F11 (app provided) or Windows+Shift+Enter (system provided) keyboard shortcut to toggle full screen, the button's icon and tooltip don't change. The app should be listening to SizeChanged event to determine if the window is in full screen mode or not.

**Comment by JaiganeshKumaran** [comment]
Okay the tooltip is static (just says enter or exit full screen) but the icon is based on the mode.

**Comment by JohnnyWestlake** [comment]
Should be irrelevant for the upcoming build as the button has been removed / replaced with a menu button instead.
