### ISSUE TITLE
Error while searching for a character

### ISSUE THREAD

**Issue by Eigi** [character-map-uwp/Character-Map-UWP#240]
- Entered "U ring" in the search box
- Selected "Latin capital letter U with ring" from the drop down menu

```
Sequence contains no matching element
   at CharacterMap.Views.FontMapView.SearchBox_SuggestionChosen(AutoSuggestBox, AutoSuggestBoxSuggestionChosenEventArgs) + 0x107
   at CharacterMap!<BaseAddress>+0x50f2ee
   at __Interop.Intrinsics.HasThisCall__23[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at CharacterMap!<BaseAddress>+0x5af0c3

```

**OS Version**: 10.0.19045.2604
**OS Architecture**: X64
**App Version**: 2023.1.2.0
**App Culture**: de-DE

**Comment by JohnnyWestlake** [comment]
@Eigi thanks for the report! I'm trying to reproduce this at the moment, do you happen to recall what font this happened with? Thanks
