### ISSUE TITLE
Settings - Character Search: "Maximum search results" stuck at 31

### ISSUE THREAD

**Issue by mileso** [character-map-uwp/Character-Map-UWP#253]
I've previously increased the **_Character Search_** "_Maximum search results_" value in **Settings** but it has reset to 31 and I cannot change the value.
### Details:   Character Map UWP - 2023.03.0.0 (X64)
The app had stopped responding and it took several attempts to kill and restart the process until I was able to get the app to start and become visible in the foreground.  I don't know if that was related, but shortly after this I noticed the number of search results had decreased from the value I previously saved (although it is possible that this change had gone unnoticed for several days, possibly since the last release).  When I went to change the value it was set to 31.  I typed in 999 in the textbox and it changed the value to 100.  I viewed another couple of setting pages and then under **_About_** I clicked on "_Restart app_." When the app restarted the setting was not saved and it was still 31.  Now after typing into the textbox it will immediately change back to 31 and the up and down buttons have no effect.

**Comment by JohnnyWestlake** [comment]
Thanks for the report, looks like I broke this and language changing in the last update. I've put the fix in, will see if I can merge it into master after I've finished some other work next week.
