### ISSUE TITLE
Cloud fonts are gone now(not to be seen)

### ISSUE THREAD

**Issue by SlippingFingers** [character-map-uwp/Character-Map-UWP#255]
First of all, thank you very much for your great app! I've used your character map uwp since two years ago. Last week I started using the app again on Windows 10 system. And the app used to show all the fonts I have, but recently while I was watching the app that's showing all the fonts right on my eyes, and what I did was just reloading the cloud fonts. And that made the problem. Character Map UWP doesn't show the cloud fonts I have now. I've searched the way to downgrade but it was not possible. I hope next time you fix the code for the Character Map UWP, please let it have all the power it used to have. Thank you!

**Comment by JohnnyWestlake** [comment]
Cloud fonts should still show up (though the search filter was removed for performance reasons). 

@SlippingFingers  Could you let me know what provider you're using for cloud fonts? That way I can test if it's still working with your set up

**Comment by SlippingFingers** [comment]
Korean company's fonts. Please check your email for more info. Thank you!

**Comment by SlippingFingers** [comment]
Korean /fonts. Sandoll Company.
Please check with this id and password.

webpage : https://www.sandollcloud.com/
id: ***@***.***
passwd: 9871Steps9871


2023년 5월 3일 (수) 오후 6:37, JohnnyWestlake ***@***.***>님이 작성:

**Comment by JohnnyWestlake** [comment]
I've been testing this today using lots of builds going back to 2018, and none of them can load fonts from SandollCloud. Whataever method they are loading font's into Windows isn't using the modern DirectWrite font loading system that CharacterMap is relies upon, so current I have no solution - but still testing!

**Comment by SlippingFingers** [comment]
Thank you for your effort. Sandoll seems to be a very strict company for its fonts not to be seen from Character Map UWP. Thank you anyway for taking your time!
