### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by JVariance** [character-map-uwp/Character-Map-UWP#261]
- [x] ~Full Name~
- [x] ~Designer~
- [x] ~Version Strings~
- [x] ~Manufacturer~
- [x] ~Trademark~
- [x] ~Copyright Notice~
- [x] ~License Description~
- [ ]  All strings from glyph variants popup

**Comment by dzl333** [comment]
Menu item "Restore" (full screen) in top left menu is missing too.
![图片](https://github.com/character-map-uwp/Character-Map-UWP/assets/157206155/a273b1a9-b210-46c9-a967-3c8cfd04d8b2)
