### ISSUE TITLE
Bug: Some searches result in no results

### ISSUE THREAD

**Issue by kmgallahan** [character-map-uwp/Character-Map-UWP#286]
### Discussed in https://github.com/character-map-uwp/Character-Map-UWP/discussions/280

Originally brought up in the discussion above, promoting to a bug now though:

---

Is it me or does search not work in certain situations?

Example: Select 'Segoe Fluent Icons', type 'Add' into the search box, no results. Same for 'A', 'Ad'...

Counterpoint: Type 'Copy', it works, 'Co' works, 'Cop' works...

This is with max search results at 250 as well.

The problem is probably related to some characters showing up in the HEX codes which are also getting searched, thus overwhelming the search.

Perhaps a search setting toggle to turn on/off searching hex codes would be useful here? I'm not sure how many people are trying to search by partial hex codes at all...

**Comment by JohnnyWestlake** [comment]
https://github.com/character-map-uwp/Character-Map-UWP/commit/21577d62e528e0f62d19d2088c48e3850a9498bb
