### ISSUE TITLE
Bug: App hangs when search box with text is clicked after switching fonts

### ISSUE THREAD

**Issue by kmgallahan** [character-map-uwp/Character-Map-UWP#293]
Repro steps:

1. Go to Segoe UI font
2. Trye 'refresh' into the search box (or any term that has no results)
3. Go to Segoe Fluent Icons
4. Click the search box

Result: App is no longer interactive, although shimmer still appears

Note: I think the prior search having no results is a requirement to trigger the bug

**Comment by JohnnyWestlake** [comment]
I can't repro this on 3 different machine rn, but I'll try find some more to try on...

**Comment by kmgallahan** [comment]
Try leaving text in the search box, switching between fonts, and clicking the box. Do this multiple times.

On trying to repro I noticed it doesn't happen every after every switch, but it will eventually occur after 1-10 switches.

It also seems to only occur when switching to Segoe Fluent Icons or Segoe MDL2 Assets, although I haven't done an exhaustive trial. And it does also seem to require going from no search results to where there should be some.

Specifically, the focus rect doesn't appear on the search box as expected, no search flyout appears, and the rest of the UI can't be interacted with.

**Comment by JohnnyWestlake** [comment]
@kmgallahan Does this still occur with the latest build? I could never get it to repro, but I did change some thing in the last build regarding the search UI

**Comment by kmgallahan** [comment]
@JohnnyWestlake Could not get it to repro just now, so I'll go ahead and close this issue. Thanks for your hard work 👍
