### ISSUE TITLE
The character list and font list tooltip animations seem to come with unwanted flashing

### ISSUE THREAD

**Issue by dzl333** [character-map-uwp/Character-Map-UWP#336]
And this happens with the animation option disabled in the settings

**Comment by JohnnyWestlake** [comment]
Thanks, any chance you can post a small video of this and what hardware you're using? I cannot reproduce on a Surface Go / Surface Studio / Surface Laptop Studio / Samsung Galaxy GO ARM

**Comment by dzl333** [comment]
I'm so sorry. I made a mistake in my wording.

NOT the font list in main window. I mean the font list in Settings - Collections, select/create a collection. And hover on font list below.

https://github.com/character-map-uwp/Character-Map-UWP/assets/157206155/423e3aba-8dae-4abb-920d-fc2cf09f470c


Character list:

https://github.com/character-map-uwp/Character-Map-UWP/assets/157206155/75a34ec9-7010-4279-890b-59f7c61f518e

https://github.com/character-map-uwp/Character-Map-UWP/assets/157206155/1c9b3be3-1787-4c32-b2ba-6098245af08c



UI button tooltip:

https://github.com/character-map-uwp/Character-Map-UWP/assets/157206155/f1d10501-23f5-4a19-8eb7-74a622b19bd2




The current part of the Tooltip animation (not affected by the animation options):
Appears and disappears without any animation. And then fade in from small to large.

Desired behavior (animation options off):
Without any animations.

Desired behavior (animation options on):
From small to big fade in.

**Comment by dzl333** [comment]
https://github.com/character-map-uwp/Character-Map-UWP/assets/157206155/e1f11416-65de-405c-b5f7-ca99726b8495

**Comment by JohnnyWestlake** [comment]
Dev note: system ToolTips styles are bad, see if can switch to using VisualTransition
