### ISSUE TITLE
Opening the Ramp View CharacterPickerButton freezes the app

### ISSUE THREAD

**Issue by United600** [character-map-uwp/Character-Map-UWP#344]
On the Windows 10 and Classic Windows themes clicking the `CharacterPickerButton` freezes, and eventually crashes, the app.

https://github.com/character-map-uwp/Character-Map-UWP/assets/698155/5dec4c8d-1196-4602-b233-ab3ccd85e6f6

**Comment by JohnnyWestlake** [comment]
dev note: missing DefaultThemeGridViewItemStyle
