### ISSUE TITLE
Mouse wheel support regression?

### ISSUE THREAD

**Issue by catherdersoftware** [character-map-uwp/Character-Map-UWP#36]
Version 2019.2.0.0, pushed out over the past couple of days. Mouse wheel support has regressed. The thin scroll bar moves up and down but the glyphs remain stationary. I can move the mouse pointer to the scroll bar; it widens, and I can drag to scroll.

This is under Windows 10 1809, which I upgraded a couple of days ago. Very similar to Issue #30 as originally reported..

Arrow keys do work.

**Comment by yoshiask** [comment]
This issue is still present sometimes in v2020.1.2.0 in Windows version 1909
