### ISSUE TITLE
App displays font weights that don't exist

### ISSUE THREAD

**Issue by callmeTayyy** [character-map-uwp/Character-Map-UWP#364]
### Expected Behavior

A font like 'Segoe Fluent Icons' or 'Webdings' should have only one weight

### Actual Behavior

The app creates additional font weights for every font, even when it has only one. It adds a Bold and multiple Oblique weights.

![Screenshot_20241104_201038218](https://github.com/user-attachments/assets/f233f254-2b7d-481a-a9e9-f62266db6a97)

### Steps to reproduce

1. Fonts with one weight.
    - Go to a font like 'Segoe Fluent Icons', 'Segoe MDL2 Assets', 'Webdings' or 'Wingdings'.
    - Notice that instead of one weight there are four.
2. Fonts with multiple weights.
    - Go to a font like 'Cascadia Mono' or 'Segoe UI'.
    - Notice that instead of 12 weights there are 18.

### Details

- Character Map UWP Version 2024.7.0.0 (X64)
- Windows 11 24H2 (Build 26100.2033)

**Comment by JohnnyWestlake** [comment]
For future reference: this is actually a change in how DirectWrite works, introduced in Windows 11 24H2

**Comment by callmeTayyy** [comment]
@JohnnyWestlake thanks for looking into it, the ability to hide those fonts is a welcome addition ☺️
